### ISSUE TITLE
How can I use your style file (.less) inside my react typescript project? 

### ISSUE THREAD

**Issue by SimonGribert** [react-component/cascader#169]
I'm using it in a project with: 
material-ui
react
typescript
rc-cascader

and it looks like this:
![image](https://user-images.githubusercontent.com/69861148/123188041-a2b93c00-d49b-11eb-9e1c-267a523dc906.png)

**Comment by NoCtrlZ1110** [comment]
@SimonGribert , i have the same issue, how can u fix that?
Thank u
