### ISSUE TITLE
Multiple 模式下 半选中状态丢失

### ISSUE THREAD

**Issue by horseson2018** [react-component/cascader#228]
![image](https://user-images.githubusercontent.com/46315787/147446543-0865b1fe-1448-4347-922a-75eb756bbdd9.png)

**Comment by horseson2018** [comment]
[PR](https://github.com/react-component/cascader/pull/229)

**Comment by horseson2018** [comment]
antd的cascader竟然没有这问题，不是基于这个仓库做的么🧐

**Comment by asmallxx** [comment]
想问下这个属性怎么使用呢？目前我需要用这个库实现多选级联，但我没有在文档里找到这个可多选的属性

**Comment by horseson2018** [comment]
> 想问下这个属性怎么使用呢？目前我需要用这个库实现多选级联，但我没有在文档里找到这个可多选的属性

checkable设为true就好，话说项目里为啥不直接用antd🧐

**Comment by asmallxx** [comment]
> 

出于某些原因，团队要求不使用antd，十分感谢你的及时回复~
