### ISSUE TITLE
Got typescript error when set strictFunctionTypes.

### ISSUE THREAD

**Issue by xiaoshuangLi** [react-component/cascader#234]
The ```SingleCascaderProps.onChange``` conflicts with ```BaseCascaderProps.onChange``` when i set typescript ```compilerOptions.strict``` or ```compilerOptions.strictFunctionTypes```.

```js
// tsconfig.json
// rc-cascader@3.0.0-alpha.6
{
  "compilerOptions": {
    "jsx": "react",
    "target": "ES5",
    "module": "commonjs",
    "lib": ["dom", "es2017", "ES2018", "ES2019", "ES2020"],
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "declaration": true,
    "importHelpers": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "downlevelIteration": true,
    // "strict": true,
    "strictFunctionTypes": true,
    "outDir": "./lib",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "moduleResolution": "node"
  },
}
```

![image](https://user-images.githubusercontent.com/12060054/148715152-beeb8b68-d535-4f31-bbf0-4acf8bcc0b1b.png)

**Comment by Hunnisoturi** [comment]
Having the same issue, `MultipleeCascaderProps<OptionType>` throwing the same error.

**Comment by lourain** [comment]
I having the same issue,too. **I comment the line which include of  `onChange`  in  interface `BaseOptionType`.**
 because   `MultipleCascaderProps<OptionType>` and `SingleCascaderProps<OptionType>`  also defined  `onChange` prop.

Hope the author can revise it in time,thx!
