### ISSUE TITLE
popupClassName 还是 dropdownClassName ？

### ISSUE THREAD

**Issue by dcycurry** [react-component/cascader#476]
现在使用antd@4.24.16，Cascader组件使用popupClassName或者dropdownClassName都提示deprecated，到底用哪个
rc-cascader
`
/** @deprecated Use `dropdownClassName` instead */
  
popupClassName?: string;
  dropdownClassName?: string;
`

antd
`
/**
   * @deprecated `dropdownClassName` is deprecated which will be removed in next major
   *   version.Please use `popupClassName` instead.
   */
  dropdownClassName?: string;
`

**Comment by Wxh16144** [comment]
4.x 应该还是优先推荐用 `dropdownClassName`， antd 侧的弃用提示是为 5.x 做准备的， rc-xxx 的弃用提示，其实和 antd 没啥关系。

准确来说 4.x 用 dropdownClassName 和 popupClassName 都行
