### ISSUE TITLE
disabled为true时，不应该显示右侧清空icon

### ISSUE THREAD

**Issue by luolonghao** [react-component/cascader#8]
隐藏一下icon

**Comment by luolonghao** [comment]
加一个prop控制是否显示右侧icon更好一些，有些场景不需要这个清空功能。

**Comment by luolonghao** [comment]
晕，原来是antd的特性

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/6d7f571c1dc7fd1c63736bb1fc40c2300600cbc6
